version: "3.7"
services:

  auth:
    image: starcraft-auth
    env_file:
      - env_vars.txt

  web:
    image: starcraft-web

  api:
    image: starcraft-api

  nginx:
    image: starcraft-nginx
    ports:
      - "8080:80"
      - "8081:443"

  sql:
    image: starcraft-sql
    volumes:
      - /run/desktop/mnt/host/c/MyProjects/StarcraftRPG/App/sql/store:/var/opt/mssql/data
    ports:
      - "8633:1433"
